### ISSUE TITLE
undefined method `keys'

### ISSUE THREAD

**Issue by vinnyglennon** [odlp/simplify_rb#2]
pry(main)>require 'simplify_rb'
=> false

[7] pry(main)> points = {x: 51.5256, y: -0.0875}
=> {:x=>51.5256, :y=>-0.0875}
[8] pry(main)> SimplifyRb.simplify(points, 1)
NoMethodError: undefined method `keys' for [:x, 51.5256]:Array
from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/simplify_rb-0.1.0/lib/simplify_rb.rb:8:in`block in simplify'

**Comment by vinnyglennon** [comment]
Gemfile.lock:  simplify_rb (0.1.0)

**Comment by odlp** [comment]
Hi @vinnyglennon the error is because 'points' needs to be an array: 

`points = [{x: 51.5256, y: -0.0875}]`

Sorry the readme was unclear about this (I've updated it now with a clearer example).
